# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
matrix:
  allow_failures:
    - os: osx
    - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PiecewiseDeterministicMarkovProcesses");include(Pkg.dir("PiecewiseDeterministicMarkovProcesses")*"/test/ci_setup.jl"); Pkg.test("PiecewiseDeterministicMarkovProcesses"; coverage=true)'
after_success:
  - julia -e 'using Pkg;cd(Pkg.dir("PiecewiseDeterministicMarkovProcesses")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; ps=PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'using Pkg;cd(Pkg.dir("PiecewiseDeterministicMarkovProcesses")); include(joinpath("docs", "make.jl"))'
